on: release
name: Build Release

jobs:
  binaries:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        GOOS: ['darwin', 'linux', 'windows']
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: arm64
          GOOS: ${{ matrix.GOOS }}